language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
cache:
  apt: true
  directories:
    - $HOME/.pip-cache/
before_install:
  - sudo apt-get update
  - sudo apt-get autoremove
  - sudo apt-get install python-numpy python-scipy python-imaging python-opencv python-pyside python-qt4 libopencv-dev ffmpeg libdc1394-22-dev --fix-missing
install:
  - pip2 install -r requirements.txt --download-cache $HOME/.pip-cache
  - pip2 install coveralls --download-cache $HOME/.pip-cache
script:
  - make test
notifications:
  email: false
after_success:
  coveralls
