language: python
python:
  - "2.7"
  - "3.4"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update
  - sudo apt-get install python-numpy python-scipy python-imaging python-opencv python-pyside python-qt4 libopencv-dev ffmpeg --fix-missing
install:
  - "pip2 install -r requirements.txt"
  - "pip3 install -r requirements_py3_4.txt"
script:
  - make test
notifications:
  email: false
